remote_theme: pmarsceill/just-the-docs

locale: en-US
title: "Introduction to Early Latin America"
markdown: kramdown
search_enabled: true

url: "https://chadblack.net/2019ELA" # the base hostname & protocol for your site

